export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'premium Bank',
    headLine: 'Unlimted Transaction with zero feees',
    description: 'Get access to our exclusive app that allows you to send and receive Unlimted transcations without getting charged any fees.',
    buttonLabel: 'Get Started',
    imgStart: false,
    mainImg: process.env.PUBLIC_URL + '/images/car.svg',
    alt: 'car',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Unlimted Access',
    headLine: 'Get Access no matter where you are',
    description: 'Get access to our exclusive app on any device, We have you covered no matter where you are located.',
    buttonLabel: 'Learn More',
    imgStart: true,
    mainImg: process.env.PUBLIC_URL + '/images/card.svg',
    alt: 'card',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Join our Team',
    headLine: 'Signup Now to get your bonus credits',
    description: 'Every new user will get $250 credits in their account to use them in their next purchase. Signup NOW to get yours.',
    buttonLabel: 'Start Now',
    imgStart: false,
    mainImg: process.env.PUBLIC_URL + '/images/form.svg',
    alt: 'form',
    dark: false,
    primary: false,
    darkText: true,
}